apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-raw-config
spec:
  selector:
    matchLabels:
      app: nginx-raw-config
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-raw-config
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: foo
          mountPath: "/mnt/foo"
          readOnly: true
      volumes:
      - name: foo
        configMap:
          name: my-config

